import assert from "node:assert/strict";
import { describe, it } from "node:test";
import tokenize from "../../src/tokenize/index.js";
import { loadDictionary } from "../../scripts/model.js";

const dictionary = loadDictionary();

const tests = [
  ["", [], "an empty string"],
  [
    "Đire wólf",
    [
      { id: 0, form: "Đire", misc: { at: 0 } },
      { id: 1, form: "wólf", misc: { at: 5 } },
    ],
    "diacritics or non-ASCII characters",
  ],
  [
    "TV T.V T.V. TV. TVaasdasd A&B A-B&C.D",
    [
      { id: 0, form: "TV", misc: { at: 0 } },
      { id: 1, form: "T.V", misc: { at: 3 } },
      { id: 2, form: "T.V.", misc: { at: 7 } },
      { id: 3, form: "TV", misc: { at: 12 } },
      { id: 4, form: ".", misc: { at: 14 } },
      { id: 5, form: "TVaasdasd", misc: { at: 16 } },
      { id: 6, form: "A&B", misc: { at: 26 } },
      { id: 7, form: "A-B&C.D", misc: { at: 30 } },
    ],
    "acronyms",
  ],
  [
    "It's ok",
    [
      { id: 0, form: "It", misc: { at: 0 } },
      { id: 1, form: "'s", misc: { at: 2 } },
      { id: 2, form: "ok", misc: { at: 5 } },
    ],
    "a contraction (singular)",
  ],
  [
    "We're here",
    [
      { id: 0, form: "We", misc: { at: 0 } },
      { id: 1, form: "'re", misc: { at: 2 } },
      { id: 2, form: "here", misc: { at: 6 } },
    ],
    "a contraction (plural)",
  ],
  [
    "don't",
    [
      { id: 0, form: "don", misc: { at: 0 } },
      { id: 1, form: "'t", misc: { at: 3 } },
    ],
    "a contraction with apostrophe",
  ],
  [
    "ain’t",
    [
      { id: 0, form: "ain", misc: { at: 0 } },
      { id: 1, form: "’t", misc: { at: 3 } },
    ],
    "a contraction with typographic apostrophe",
  ],
  [
    "il'gynoth",
    [{ id: 0, form: "il'gynoth", misc: { at: 0 } }],
    "a form containing a mid-apostrophe",
  ],
  [
    "John said 'shit'",
    [
      { id: 0, form: "John", misc: { at: 0 } },
      { id: 1, form: "said", misc: { at: 5 } },
      { id: 2, form: "'", misc: { at: 10 } },
      { id: 3, form: "shit", misc: { at: 11 } },
      { id: 4, form: "'", misc: { at: 15 } },
    ],
    "apostrophes as quotes",
  ],
  [
    'She said "no"',
    [
      { id: 0, form: "She", misc: { at: 0 } },
      { id: 1, form: "said", misc: { at: 4 } },
      { id: 2, form: '"', misc: { at: 9 } },
      { id: 3, form: "no", misc: { at: 10 } },
      { id: 4, form: '"', misc: { at: 12 } },
    ],
    "quotes",
  ],
  [
    "Let’s go back to the 80’s",
    [
      { id: 0, form: "Let", misc: { at: 0 } },
      { id: 1, form: "’s", misc: { at: 3 } },
      { id: 2, form: "go", misc: { at: 6 } },
      { id: 3, form: "back", misc: { at: 9 } },
      { id: 4, form: "to", misc: { at: 14 } },
      { id: 5, form: "the", misc: { at: 17 } },
      { id: 6, form: "80", misc: { at: 21 } },
      { id: 7, form: "’s", misc: { at: 23 } },
    ],
    "proper apostrophes (RIGHT SINGLE QUOTATION MARK)",
  ],
  [
    "I ain't cleaning that up",
    [
      { id: 0, form: "I", misc: { at: 0 } },
      { id: 1, form: "ain", misc: { at: 2 } },
      { id: 2, form: "'t", misc: { at: 5 } },
      { id: 3, form: "cleaning", misc: { at: 8 } },
      { id: 4, form: "that", misc: { at: 17 } },
      { id: 5, form: "up", misc: { at: 22 } },
    ],
    "fused words",
  ],
  [
    "Is he gunna do it?",
    [
      { id: 0, form: "Is", misc: { at: 0 } },
      { id: 1, form: "he", misc: { at: 3 } },
      { id: 2, form: "gun", misc: { at: 6 } },
      { id: 3, form: "na", misc: { at: 9 } },
      { id: 4, form: "do", misc: { at: 12 } },
      { id: 5, form: "it", misc: { at: 15 } },
      { id: 6, form: "?", misc: { at: 17 } },
    ],
    "a fused contraction (slang)",
  ],
  [
    "I'm gon-na go now",
    [
      { id: 0, form: "I", misc: { at: 0 } },
      { id: 1, form: "'m", misc: { at: 1 } },
      { id: 2, form: "gon-na", misc: { at: 4 } },
      { id: 3, form: "go", misc: { at: 11 } },
      { id: 4, form: "now", misc: { at: 14 } },
    ],
    "a fused contraction with an unnecessary hyphen",
  ],
  [
    "a well-written essay",
    [
      { id: 0, form: "a", misc: { at: 0 } },
      { id: 1, form: "well-written", misc: { at: 2 } },
      { id: 2, form: "essay", misc: { at: 15 } },
    ],
    "a form with a hyphen",
  ],
  [
    "let's have a vis-a-vis",
    [
      { id: 0, form: "let", misc: { at: 0 } },
      { id: 1, form: "'s", misc: { at: 3 } },
      { id: 2, form: "have", misc: { at: 6 } },
      { id: 3, form: "a", misc: { at: 11 } },
      { id: 4, form: "vis-a-vis", misc: { at: 13 } },
    ],
    "a form with many hyphens",
  ],
  [
    "I'd vote no on O-Care",
    [
      { id: 0, form: "I", misc: { at: 0 } },
      { id: 1, form: "'d", misc: { at: 1 } },
      { id: 2, form: "vote", misc: { at: 4 } },
      { id: 3, form: "no", misc: { at: 9 } },
      { id: 4, form: "on", misc: { at: 12 } },
      { id: 5, form: "O-Care", misc: { at: 15 } },
    ],
    "a form with a hyphen that's not in the dictionary",
  ],
  [
    "-sponsored sponsored-",
    [
      { id: 0, form: "-", misc: { at: 0 } },
      { id: 1, form: "sponsored", misc: { at: 1 } },
      { id: 2, form: "sponsored", misc: { at: 11 } },
      { id: 3, form: "-", misc: { at: 20 } },
    ],
    "a form with leading or trailing hyphen",
  ],
  [
    "ads in location revolution - 11-34",
    [
      { id: 0, form: "ads", misc: { at: 0 } },
      { id: 1, form: "in", misc: { at: 4 } },
      { id: 2, form: "location", misc: { at: 7 } },
      { id: 3, form: "revolution", misc: { at: 16 } },
      { id: 4, form: "-", misc: { at: 27 } },
      { id: 5, form: "11", misc: { at: 29 } },
      { id: 6, form: "-", misc: { at: 31 } },
      { id: 7, form: "34", misc: { at: 32 } },
    ],
    "a hyphen between numbers",
  ],
  [
    "Why? Yes!!!",
    [
      { id: 0, form: "Why", misc: { at: 0 } },
      { id: 1, form: "?", misc: { at: 3 } },
      { id: 2, form: "Yes", misc: { at: 5 } },
      { id: 3, form: "!", misc: { at: 8 } },
      { id: 4, form: "!", misc: { at: 9 } },
      { id: 5, form: "!", misc: { at: 10 } },
    ],
    "sentence terminators",
  ],
  [
    "one, two, and three; a, b, and c; 1, 2, and 3",
    [
      { id: 0, form: "one", misc: { at: 0 } },
      { id: 1, form: ",", misc: { at: 3 } },
      { id: 2, form: "two", misc: { at: 5 } },
      { id: 3, form: ",", misc: { at: 8 } },
      { id: 4, form: "and", misc: { at: 10 } },
      { id: 5, form: "three", misc: { at: 14 } },
      { id: 6, form: ";", misc: { at: 19 } },
      { id: 7, form: "a", misc: { at: 21 } },
      { id: 8, form: ",", misc: { at: 22 } },
      { id: 9, form: "b", misc: { at: 24 } },
      { id: 10, form: ",", misc: { at: 25 } },
      { id: 11, form: "and", misc: { at: 27 } },
      { id: 12, form: "c;", misc: { at: 31 } },
      { id: 13, form: "1", misc: { at: 34 } },
      { id: 14, form: ",", misc: { at: 35 } },
      { id: 15, form: "2", misc: { at: 37 } },
      { id: 16, form: ",", misc: { at: 38 } },
      { id: 17, form: "and", misc: { at: 40 } },
      { id: 18, form: "3", misc: { at: 44 } },
    ],
    "terminators (but not sentence terminators)",
  ],
  [
    "He said: yes",
    [
      { id: 0, form: "He", misc: { at: 0 } },
      { id: 1, form: "said", misc: { at: 3 } },
      { id: 2, form: ":", misc: { at: 7 } },
      { id: 3, form: "yes", misc: { at: 9 } },
    ],
    "colons",
  ],
  [
    "along with CM7.5)",
    [
      { id: 0, form: "along", misc: { at: 0 } },
      { id: 1, form: "with", misc: { at: 6 } },
      { id: 2, form: "CM7", misc: { at: 11 } },
      { id: 3, form: ".", misc: { at: 14 } },
      { id: 4, form: "5", misc: { at: 15 } },
      { id: 5, form: ")", misc: { at: 16 } },
    ],
    "a form with punctuation characters in the middle and end",
  ],
  [
    "I want two % to eight%",
    [
      { id: 0, form: "I", misc: { at: 0 } },
      { id: 1, form: "want", misc: { at: 2 } },
      { id: 2, form: "two", misc: { at: 7 } },
      { id: 3, form: "%", misc: { at: 11 } },
      { id: 4, form: "to", misc: { at: 13 } },
      { id: 5, form: "eight", misc: { at: 16 } },
      { id: 6, form: "%", misc: { at: 21 } },
    ],
    "percentages",
  ],
  [
    "set NODE_ENV",
    [
      { id: 0, form: "set", misc: { at: 0 } },
      { id: 1, form: "NODE_ENV", misc: { at: 4 } },
    ],
    "connector characters inside a form",
  ],
  [
    "looking for **experienced** developers",
    [
      { id: 0, form: "looking", misc: { at: 0 } },
      { id: 1, form: "for", misc: { at: 8 } },
      { id: 2, form: "**", misc: { at: 12 } },
      { id: 3, form: "experienced", misc: { at: 14 } },
      { id: 4, form: "**", misc: { at: 25 } },
      { id: 5, form: "developers", misc: { at: 28 } },
    ],
    "adjacent non-alphabetic characters",
  ],
  [
    "&amp; &lt; &gt; &quot; &#39; &nbsp; &#8211; &#8212;",
    [
      { id: 0, form: "&amp;", misc: { at: 0 } },
      { id: 1, form: "&lt;", misc: { at: 6 } },
      { id: 2, form: "&gt;", misc: { at: 11 } },
      { id: 3, form: "&quot;", misc: { at: 16 } },
      { id: 4, form: "&#39;", misc: { at: 23 } },
      { id: 5, form: "&nbsp;", misc: { at: 29 } },
      { id: 6, form: "&#8211;", misc: { at: 36 } },
      { id: 7, form: "&#8212;", misc: { at: 44 } },
    ],
    "HTML entities",
  ],
  [
    "i <3 u :)",
    [
      { id: 0, form: "i", misc: { at: 0 } },
      { id: 1, form: "<3", misc: { at: 2 } },
      { id: 2, form: "u", misc: { at: 5 } },
      { id: 3, form: ":)", misc: { at: 7 } },
    ],
    "words and emoticons",
  ],
  [
    "=D :> ;) :o| :P :c (-:",
    [
      { id: 0, form: "=D", misc: { at: 0 } },
      { id: 1, form: ":>", misc: { at: 3 } },
      { id: 2, form: ";)", misc: { at: 6 } },
      { id: 3, form: ":o|", misc: { at: 9 } },
      { id: 4, form: ":P", misc: { at: 13 } },
      { id: 5, form: ":c", misc: { at: 16 } },
      { id: 6, form: "(-:", misc: { at: 19 } },
    ],
    "emoticons",
  ],
  [
    "From -1 to 1",
    [
      { id: 0, form: "From", misc: { at: 0 } },
      { id: 1, form: "-1", misc: { at: 5 } },
      { id: 2, form: "to", misc: { at: 8 } },
      { id: 3, form: "1", misc: { at: 11 } },
    ],
    "numbers",
  ],
  [
    "From -3.14 to 3.14",
    [
      { id: 0, form: "From", misc: { at: 0 } },
      { id: 1, form: "-3.14", misc: { at: 5 } },
      { id: 2, form: "to", misc: { at: 11 } },
      { id: 3, form: "3.14", misc: { at: 14 } },
    ],
    "numbers with decimal point",
  ],
  [
    "$40,000",
    [
      { id: 0, form: "$", misc: { at: 0 } },
      { id: 1, form: "40,000", misc: { at: 1 } },
    ],
    "A number with a comma is tokenized as a single token",
  ],
  [
    "$40.00",
    [
      { id: 0, form: "$", misc: { at: 0 } },
      { id: 1, form: "40.00", misc: { at: 1 } },
    ],
    "A number with a decimal point is tokenized as a single token",
  ],
  [
    "$40,000.00",
    [
      { id: 0, form: "$", misc: { at: 0 } },
      { id: 1, form: "40,000.00", misc: { at: 1 } },
    ],
    "A number with a comma and a decimal point is tokenized as a single token",
  ],
  [
    "6E6 died",
    [
      { id: 0, form: "6E6", misc: { at: 0 } },
      { id: 1, form: "died", misc: { at: 4 } },
    ],
    "numbers with exponent",
  ],
  [
    "250e3 died",
    [
      { id: 0, form: "250e3", misc: { at: 0 } },
      { id: 1, form: "died", misc: { at: 6 } },
    ],
    "numbers with exponent in lowercase",
  ],
  [
    "6e+6 died",
    [
      { id: 0, form: "6e+6", misc: { at: 0 } },
      { id: 1, form: "died", misc: { at: 5 } },
    ],
    "numbers with positive exponent",
  ],
  [
    "6e-6 died",
    [
      { id: 0, form: "6e-6", misc: { at: 0 } },
      { id: 1, form: "died", misc: { at: 5 } },
    ],
    "numbers with negative exponent",
  ],
  [
    "1996 04 22; 22 April 1996; Sunday, 22 Apr 1996; april 22 1996",
    [
      { id: 0, form: "1996", misc: { at: 0 } },
      { id: 1, form: "04", misc: { at: 5 } },
      { id: 2, form: "22", misc: { at: 8 } },
      { id: 3, form: ";", misc: { at: 10 } },
      { id: 4, form: "22", misc: { at: 12 } },
      { id: 5, form: "April", misc: { at: 15 } },
      { id: 6, form: "1996", misc: { at: 21 } },
      { id: 7, form: ";", misc: { at: 25 } },
      { id: 8, form: "Sunday", misc: { at: 27 } },
      { id: 9, form: ",", misc: { at: 33 } },
      { id: 10, form: "22", misc: { at: 35 } },
      { id: 11, form: "Apr", misc: { at: 38 } },
      { id: 12, form: "1996", misc: { at: 42 } },
      { id: 13, form: ";", misc: { at: 46 } },
      { id: 14, form: "april", misc: { at: 48 } },
      { id: 15, form: "22", misc: { at: 54 } },
      { id: 16, form: "1996", misc: { at: 57 } },
    ],
    "days, months and years as split with spaces",
  ],
  [
    "1996,April,22; 1996,apr,22",
    [
      { id: 0, form: "1996", misc: { at: 0 } },
      { id: 1, form: ",", misc: { at: 4 } },
      { id: 2, form: "April", misc: { at: 5 } },
      { id: 3, form: ",", misc: { at: 10 } },
      { id: 4, form: "22", misc: { at: 11 } },
      { id: 5, form: ";", misc: { at: 13 } },
      { id: 6, form: "1996", misc: { at: 15 } },
      { id: 7, form: ",", misc: { at: 19 } },
      { id: 8, form: "apr", misc: { at: 20 } },
      { id: 9, form: ",", misc: { at: 23 } },
      { id: 10, form: "22", misc: { at: 24 } },
    ],
    "days, months and years as split with commas",
  ],
  [
    "1984-12-31 31-12-1984 12-31-1984 1984/12/31 31/12/1984 12/31/1984 1984.12.31 31.12.1984 12.31.1984",
    [
      { id: 0, form: "1984-12-31", misc: { at: 0 } },
      { id: 1, form: "31-12-1984", misc: { at: 11 } },
      { id: 2, form: "12-31-1984", misc: { at: 22 } },
      { id: 3, form: "1984/12/31", misc: { at: 33 } },
      { id: 4, form: "31/12/1984", misc: { at: 44 } },
      { id: 5, form: "12/31/1984", misc: { at: 55 } },
      { id: 6, form: "1984.12.31", misc: { at: 66 } },
      { id: 7, form: "31.12.1984", misc: { at: 77 } },
      { id: 8, form: "12.31.1984", misc: { at: 88 } },
    ],
    "dates",
  ],
  [
    "1984-01-01 1984-01-01T12 1984-01-01T12:00 1984-01-01T12:00:00 1984-01-01T12:00:00.000Z",
    [
      { id: 0, form: "1984-01-01", misc: { at: 0 } },
      { id: 1, form: "1984-01-01T12", misc: { at: 11 } },
      { id: 2, form: "1984-01-01T12:00", misc: { at: 25 } },
      { id: 3, form: "1984-01-01T12:00:00", misc: { at: 42 } },
      { id: 4, form: "1984-01-01T12:00:00.000Z", misc: { at: 62 } },
    ],
    "ISO 8601 dates",
  ],
  [
    "from 1984-01-01T00:00:00Z to 2094-12-31T23:59:59.000Z",
    [
      { id: 0, form: "from", misc: { at: 0 } },
      { id: 1, form: "1984-01-01T00:00:00Z", misc: { at: 5 } },
      { id: 2, form: "to", misc: { at: 26 } },
      { id: 3, form: "2094-12-31T23:59:59.000Z", misc: { at: 29 } },
    ],
    "RFC 3339 datetimes",
  ],
  [
    "1984-12 12-1984 1984/12 12/1984 1984.12 12.1984",
    [
      { id: 0, form: "1984-12", misc: { at: 0 } },
      { id: 1, form: "12-1984", misc: { at: 8 } },
      { id: 2, form: "1984/12", misc: { at: 16 } },
      { id: 3, form: "12/1984", misc: { at: 24 } },
      { id: 4, form: "1984.12", misc: { at: 32 } },
      { id: 5, form: "12.1984", misc: { at: 40 } },
    ],
    "months",
  ],
  [
    "from 8:00 to 20:00",
    [
      { id: 0, form: "from", misc: { at: 0 } },
      { id: 1, form: "8:00", misc: { at: 5 } },
      { id: 2, form: "to", misc: { at: 10 } },
      { id: 3, form: "20:00", misc: { at: 13 } },
    ],
    "times",
  ],
  [
    "at five o'clock",
    [
      { id: 0, form: "at", misc: { at: 0 } },
      { id: 1, form: "five", misc: { at: 3 } },
      { id: 2, form: "o'", misc: { at: 8 } },
      { id: 3, form: "clock", misc: { at: 10 } },
    ],
    "times as words",
  ],
  [
    "The score was ninety-nine to ten",
    [
      { id: 0, form: "The", misc: { at: 0 } },
      { id: 1, form: "score", misc: { at: 4 } },
      { id: 2, form: "was", misc: { at: 10 } },
      { id: 3, form: "ninety-nine", misc: { at: 14 } },
      { id: 4, form: "to", misc: { at: 26 } },
      { id: 5, form: "ten", misc: { at: 29 } },
    ],
    "times with hyphens",
  ],
  [
    "2$; $2; USD 2; 2 dollars; 2€; €2; EUR 2; 2 euros",
    [
      { id: 0, form: "2", misc: { at: 0 } },
      { id: 1, form: "$", misc: { at: 1 } },
      { id: 2, form: ";", misc: { at: 2 } },
      { id: 3, form: "$", misc: { at: 4 } },
      { id: 4, form: "2", misc: { at: 5 } },
      { id: 5, form: ";", misc: { at: 6 } },
      { id: 6, form: "USD", misc: { at: 8 } },
      { id: 7, form: "2", misc: { at: 12 } },
      { id: 8, form: ";", misc: { at: 13 } },
      { id: 9, form: "2", misc: { at: 15 } },
      { id: 10, form: "dollars", misc: { at: 17 } },
      { id: 11, form: ";", misc: { at: 24 } },
      { id: 12, form: "2", misc: { at: 26 } },
      { id: 13, form: "€", misc: { at: 27 } },
      { id: 14, form: ";", misc: { at: 28 } },
      { id: 15, form: "€", misc: { at: 30 } },
      { id: 16, form: "2", misc: { at: 31 } },
      { id: 17, form: ";", misc: { at: 32 } },
      { id: 18, form: "EUR", misc: { at: 34 } },
      { id: 19, form: "2", misc: { at: 38 } },
      { id: 20, form: ";", misc: { at: 39 } },
      { id: 21, form: "2", misc: { at: 41 } },
      { id: 22, form: "euros", misc: { at: 43 } },
    ],
    "currencies",
  ],
  [
    "£5-£10",
    [
      { id: 0, form: "£", misc: { at: 0 } },
      { id: 1, form: "5", misc: { at: 1 } },
      { id: 2, form: "-", misc: { at: 2 } },
      { id: 3, form: "£", misc: { at: 3 } },
      { id: 4, form: "10", misc: { at: 4 } },
    ],
    "currency ranges",
  ],
  [
    "1234 +1234567 123456789012345 +123456789012345",
    [
      { id: 0, form: "1234", misc: { at: 0 } },
      { id: 1, form: "+1234567", misc: { at: 5 } },
      { id: 2, form: "123456789012345", misc: { at: 14 } },
      { id: 3, form: "+123456789012345", misc: { at: 30 } },
    ],
    "telephone numbers",
  ],
  [
    "754 3010 (541)754 3010 +1 541 754 3010 1 541 754 3010",
    [
      { id: 0, form: "754", misc: { at: 0 } },
      { id: 1, form: "3010", misc: { at: 4 } },
      { id: 2, form: "(", misc: { at: 9 } },
      { id: 3, form: "541", misc: { at: 10 } },
      { id: 4, form: ")", misc: { at: 13 } },
      { id: 5, form: "754", misc: { at: 14 } },
      { id: 6, form: "3010", misc: { at: 18 } },
      { id: 7, form: "+", misc: { at: 23 } },
      { id: 8, form: "1", misc: { at: 24 } },
      { id: 9, form: "541", misc: { at: 26 } },
      { id: 10, form: "754", misc: { at: 30 } },
      { id: 11, form: "3010", misc: { at: 34 } },
      { id: 12, form: "1", misc: { at: 39 } },
      { id: 13, form: "541", misc: { at: 41 } },
      { id: 14, form: "754", misc: { at: 45 } },
      { id: 15, form: "3010", misc: { at: 49 } },
    ],
    "telephone numbers formatted with spaces",
  ],
  [
    "99999-9999  00000-0000",
    [
      { id: 0, form: "99999-9999", misc: { at: 0 } },
      { id: 1, form: "00000-0000", misc: { at: 12 } },
    ],
    "US postal codes",
  ],
  [
    "TR26 2RN BT6 8NL ME7 9AA W24RT CV6 2LB",
    [
      { id: 0, form: "TR26", misc: { at: 0 } },
      { id: 1, form: "2", misc: { at: 5 } },
      { id: 2, form: "R", misc: { at: 6 } },
      { id: 3, form: "N", misc: { at: 7 } },
      { id: 4, form: "BT6", misc: { at: 9 } },
      { id: 5, form: "8", misc: { at: 13 } },
      { id: 6, form: "NL", misc: { at: 14 } },
      { id: 7, form: "ME7", misc: { at: 17 } },
      { id: 8, form: "9", misc: { at: 21 } },
      { id: 9, form: "AA", misc: { at: 22 } },
      { id: 10, form: "W24RT", misc: { at: 25 } },
      { id: 11, form: "CV6", misc: { at: 31 } },
      { id: 12, form: "2", misc: { at: 35 } },
      { id: 13, form: "LB", misc: { at: 36 } },
    ],
    "UK postal codes",
  ],
  [
    "B4V 2K4 T0E 1S2 L6Y 2N4 L8V 3Y1",
    [
      { id: 0, form: "B4V", misc: { at: 0 } },
      { id: 1, form: "2", misc: { at: 4 } },
      { id: 2, form: "K", misc: { at: 5 } },
      { id: 3, form: "4", misc: { at: 6 } },
      { id: 4, form: "T0E", misc: { at: 8 } },
      { id: 5, form: "1", misc: { at: 12 } },
      { id: 6, form: "S", misc: { at: 13 } },
      { id: 7, form: "2", misc: { at: 14 } },
      { id: 8, form: "L6Y", misc: { at: 16 } },
      { id: 9, form: "2", misc: { at: 20 } },
      { id: 10, form: "N", misc: { at: 21 } },
      { id: 11, form: "4", misc: { at: 22 } },
      { id: 12, form: "L8V", misc: { at: 24 } },
      { id: 13, form: "3", misc: { at: 28 } },
      { id: 14, form: "Y", misc: { at: 29 } },
      { id: 15, form: "1", misc: { at: 30 } },
    ],
    "UK postal codes separated by spaces",
  ],
  [
    "04001-04357  08107;  06905",
    [
      { id: 0, form: "04001-04357", misc: { at: 0 } },
      { id: 1, form: "08107", misc: { at: 13 } },
      { id: 2, form: ";", misc: { at: 18 } },
      { id: 3, form: "06905", misc: { at: 21 } },
    ],
    "DE postal codes",
  ],
  [
    "me:https://example.com/abc:me gmail@potato.com file:///lul.js mailto:jonny@company https:scammaz.com ftp://villains/johnny/evilplans",
    [
      { id: 0, form: "me:https://example.com/abc:me", misc: { at: 0 } },
      { id: 1, form: "gmail@potato.com", misc: { at: 30 } },
      { id: 2, form: "file:///lul.js", misc: { at: 47 } },
      { id: 3, form: "mailto:jonny@company", misc: { at: 62 } },
      { id: 4, form: "https:scammaz.com", misc: { at: 83 } },
      { id: 5, form: "ftp://villains/johnny/evilplans", misc: { at: 101 } },
    ],
    "URLs",
  ],
  [
    "example@domain.com  , some_mail.person@domain.es, test@outlook.com",
    [
      { id: 0, form: "example@domain.com", misc: { at: 0 } },
      { id: 1, form: ",", misc: { at: 20 } },
      { id: 2, form: "some_mail.person@domain.es", misc: { at: 22 } },
      { id: 3, form: ",", misc: { at: 48 } },
      { id: 4, form: "test@outlook.com", misc: { at: 50 } },
    ],
    "e-mails",
  ],
  [
    "firstname@exampleair.com\n    info@examplecompany.com\n    someone88@gmail.com\n    first.last1@example-recruiting.org.uk",
    [
      { id: 0, form: "firstname@exampleair.com", misc: { at: 0 } },
      { id: 1, form: "info@examplecompany.com", misc: { at: 29 } },
      { id: 2, form: "someone88@gmail.com", misc: { at: 57 } },
      {
        id: 3,
        form: "first.last1@example-recruiting.org.uk",
        misc: { at: 81 },
      },
    ],
    "e-mails (multiline)",
  ],
  [
    "Looking for a #Freelance #Sitecore #CMS #Developer.",
    [
      { id: 0, form: "Looking", misc: { at: 0 } },
      { id: 1, form: "for", misc: { at: 8 } },
      { id: 2, form: "a", misc: { at: 12 } },
      { id: 3, form: "#Freelance", misc: { at: 14 } },
      { id: 4, form: "#Sitecore", misc: { at: 25 } },
      { id: 5, form: "#CMS", misc: { at: 35 } },
      { id: 6, form: "#Developer", misc: { at: 40 } },
      { id: 7, form: ".", misc: { at: 50 } },
    ],
    "hashtags",
  ],
  [
    "Hey @user",
    [
      { id: 0, form: "Hey", misc: { at: 0 } },
      { id: 1, form: "@user", misc: { at: 4 } },
    ],
    "mentions",
  ],
  [
    "⌚",
    [{ id: 0, form: "⌚", misc: { at: 0 } }],
    "a default emoji presentation character",
  ],
  [
    "↔️",
    [{ id: 0, form: "↔️", misc: { at: 0 } }],
    "an emoji presentation sequence",
  ],
  ["👩", [{ id: 0, form: "👩", misc: { at: 0 } }], "an emoji modifier base"],
  [
    "👩🏿",
    [{ id: 0, form: "👩🏿", misc: { at: 0 } }],
    "an emoji modifier sequence",
  ],
  [
    "🇦🇨 🇸🇮🇦🇨 🇸🇯 🇸🇰 🇹🇿 🇺🇦 🇿🇼",
    [
      { id: 0, form: "🇦🇨", misc: { at: 0 } },
      { id: 1, form: "🇸🇮", misc: { at: 5 } },
      { id: 2, form: "🇦🇨", misc: { at: 9 } },
      { id: 3, form: "🇸🇯", misc: { at: 14 } },
      { id: 4, form: "🇸🇰", misc: { at: 19 } },
      { id: 5, form: "🇹🇿", misc: { at: 24 } },
      { id: 6, form: "🇺🇦", misc: { at: 29 } },
      { id: 7, form: "🇿🇼", misc: { at: 34 } },
    ],
    "emoji flag sequences",
  ],
  [
    "🏴󠁧󠁢󠁥󠁮󠁧󠁿🏴󠁧󠁢󠁳󠁣󠁴󠁿🏴󠁧󠁢󠁷󠁬󠁳󠁿🏴󠁵󠁳󠁴󠁸󠁿",
    [
      { id: 0, form: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", misc: { at: 0 } },
      { id: 1, form: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", misc: { at: 14 } },
      { id: 2, form: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", misc: { at: 28 } },
      { id: 3, form: "🏴󠁵󠁳󠁴󠁸󠁿", misc: { at: 42 } },
    ],
    "emoji tag sequences",
  ],
  [
    "#️⃣ *️⃣ 0️⃣ 1️⃣2️⃣3️⃣ 4️⃣5️⃣6️⃣ 7️⃣8️⃣9️⃣",
    [
      { id: 0, form: "#️⃣", misc: { at: 0 } },
      { id: 1, form: "*️⃣", misc: { at: 4 } },
      { id: 2, form: "0️⃣", misc: { at: 8 } },
      { id: 3, form: "1️⃣", misc: { at: 12 } },
      { id: 4, form: "2️⃣", misc: { at: 15 } },
      { id: 5, form: "3️⃣", misc: { at: 18 } },
      { id: 6, form: "4️⃣", misc: { at: 22 } },
      { id: 7, form: "5️⃣", misc: { at: 25 } },
      { id: 8, form: "6️⃣", misc: { at: 28 } },
      { id: 9, form: "7️⃣", misc: { at: 32 } },
      { id: 10, form: "8️⃣", misc: { at: 35 } },
      { id: 11, form: "9️⃣", misc: { at: 38 } },
    ],
    "emoji keycap sequences",
  ],
  [
    "🙇‍♂️🏴‍☠️",
    [
      { id: 0, form: "🙇‍♂️", misc: { at: 0 } },
      { id: 1, form: "🏴‍☠️", misc: { at: 5 } },
    ],
    "emoji zwj sequences",
  ],
  [
    "a😀󠁧󠁢󠁷󠁬󠁳󠁿 😀 😀a",
    [
      { id: 0, form: "a", misc: { at: 0 } },
      { id: 1, form: "😀", misc: { at: 1 } },
      { id: 2, form: "😀", misc: { at: 16 } },
      { id: 3, form: "😀", misc: { at: 19 } },
      { id: 4, form: "a", misc: { at: 21 } },
    ],
    "emoji adjacent to words",
  ],
  [
    "😀😀🐀🐀👧",
    [
      { id: 0, form: "😀", misc: { at: 0 } },
      { id: 1, form: "😀", misc: { at: 2 } },
      { id: 2, form: "🐀", misc: { at: 4 } },
      { id: 3, form: "🐀", misc: { at: 6 } },
      { id: 4, form: "👧", misc: { at: 8 } },
    ],
    "emoji adjacent to emoji",
  ],
  [
    "wicket Loo bc 😡 😡 😡 😡 #MIvCSK",
    [
      { id: 0, form: "wicket", misc: { at: 0 } },
      { id: 1, form: "Loo", misc: { at: 7 } },
      { id: 2, form: "bc", misc: { at: 11 } },
      { id: 3, form: "😡", misc: { at: 14 } },
      { id: 4, form: "😡", misc: { at: 17 } },
      { id: 5, form: "😡", misc: { at: 20 } },
      { id: 6, form: "😡", misc: { at: 23 } },
      { id: 7, form: "#MIvCSK", misc: { at: 26 } },
    ],
    "Twitter noise",
  ],
  [
    "SKY and Kishan keep rotating strikes. #MIvCSK",
    [
      { id: 0, form: "SKY", misc: { at: 0 } },
      { id: 1, form: "and", misc: { at: 4 } },
      { id: 2, form: "Kishan", misc: { at: 8 } },
      { id: 3, form: "keep", misc: { at: 15 } },
      { id: 4, form: "rotating", misc: { at: 20 } },
      { id: 5, form: "strikes", misc: { at: 29 } },
      { id: 6, form: ".", misc: { at: 36 } },
      { id: 7, form: "#MIvCSK", misc: { at: 38 } },
    ],
    "Twitter noise",
  ],
  [
    "He ain-t on it",
    [
      { id: 0, form: "He", misc: { at: 0 } },
      { id: 1, form: "ain-t", misc: { at: 3 } },
      { id: 2, form: "on", misc: { at: 9 } },
      { id: 3, form: "it", misc: { at: 12 } },
    ],
    "a fused word that has a noise character",
  ],
  [
    "i.e.",
    [{ id: 0, form: "i.e.", misc: { at: 0 } }],
    "a contractions that has infix full-stops and ends in full-stop",
  ],
  [
    "i.e",
    [{ id: 0, form: "i.e", misc: { at: 0 } }],
    "a contractions that has infix full-stops",
  ],
  [
    "#Trump's lawyer told Manafort he'd be taken 'care of,'",
    [
      { id: 0, form: "#Trump", misc: { at: 0 } },
      { id: 1, form: "'s", misc: { at: 6 } },
      { id: 2, form: "lawyer", misc: { at: 9 } },
      { id: 3, form: "told", misc: { at: 16 } },
      { id: 4, form: "Manafort", misc: { at: 21 } },
      { id: 5, form: "he", misc: { at: 30 } },
      { id: 6, form: "'d", misc: { at: 32 } },
      { id: 7, form: "be", misc: { at: 35 } },
      { id: 8, form: "taken", misc: { at: 38 } },
      { id: 9, form: "'", misc: { at: 44 } },
      { id: 10, form: "care", misc: { at: 45 } },
      { id: 11, form: "of", misc: { at: 50 } },
      { id: 12, form: ",", misc: { at: 52 } },
      { id: 13, form: "'", misc: { at: 53 } },
    ],
    "an initial hashtagged proper noun followed by a possessive marker",
  ],
] as [
  text: string,
  tokens: { id: number; form: string; misc: { at: number } }[],
  name: string,
][];

describe("tokenize", () => {
  tests.forEach(([text, tokens, name]) => {
    it(name, () => {
      const actualTokens = tokenize(text, { dictionary });
      assert.equal(actualTokens.length, tokens.length);
      tokens.forEach((expected, i) => {
        const actual = actualTokens[i];
        assert.equal(actual.id, expected.id);
        assert.equal(actual.form, expected.form);
        assert.equal(actual.misc.at, expected.misc.at);
      });
    });
  });
});
